# Copyright (C) 2026 Axis Communications AB, Lund, Sweden
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

"""Type stub for the Rust-native asanypath_native extension module."""

from typing import Any

# -- S3 --
async def s3_get_batch(*args: Any, **kwargs: Any) -> Any: ...
async def s3_put_batch(*args: Any, **kwargs: Any) -> Any: ...
async def s3_create_multipart(*args: Any, **kwargs: Any) -> Any: ...
async def s3_upload_part(*args: Any, **kwargs: Any) -> Any: ...
async def s3_complete_multipart(*args: Any, **kwargs: Any) -> Any: ...
async def s3_abort_multipart(*args: Any, **kwargs: Any) -> Any: ...
async def s3_copy_batch(*args: Any, **kwargs: Any) -> Any: ...
async def s3_delete_batch(*args: Any, **kwargs: Any) -> Any: ...
async def s3_exists_batch(*args: Any, **kwargs: Any) -> Any: ...
async def s3_list_batch(*args: Any, **kwargs: Any) -> Any: ...
async def s3_head_batch(*args: Any, **kwargs: Any) -> Any: ...
async def s3_is_dir(*args: Any, **kwargs: Any) -> Any: ...
async def s3_is_dir_batch(*args: Any, **kwargs: Any) -> Any: ...
async def s3_list_buckets(*args: Any, **kwargs: Any) -> Any: ...
async def s3_get_acl(*args: Any, **kwargs: Any) -> Any: ...
async def s3_put_acl(*args: Any, **kwargs: Any) -> Any: ...
async def s3_get_credentials(
    region_override: str | None,
    access_key: str | None,
    secret_key: str | None,
    session_token: str | None,
) -> tuple[str, str, str | None, str, str | None]: ...
def s3_presign(
    endpoint: str,
    bucket: str,
    key: str,
    region: str,
    access_key: str,
    secret_key: str,
    session_token: str | None = None,
    method: str | None = None,
    expires: int | None = None,
) -> str: ...

# -- GCS --
async def gcs_get_batch(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_put_batch(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_copy_batch(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_delete_batch(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_exists_batch(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_list_batch(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_head(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_head_batch(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_is_dir(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_is_dir_batch(*args: Any, **kwargs: Any) -> Any: ...
async def gcs_list_buckets(*args: Any, **kwargs: Any) -> Any: ...
def gcs_presign(
    bucket: str,
    object_path: str,
    service_account_json: str,
    method: str | None = None,
    expires: int | None = None,
) -> str: ...

# -- Azure --
async def az_get_batch(*args: Any, **kwargs: Any) -> Any: ...
async def az_put_batch(*args: Any, **kwargs: Any) -> Any: ...
async def az_put_block(*args: Any, **kwargs: Any) -> Any: ...
async def az_put_block_list(*args: Any, **kwargs: Any) -> Any: ...
async def az_copy_batch(*args: Any, **kwargs: Any) -> Any: ...
async def az_delete_batch(*args: Any, **kwargs: Any) -> Any: ...
async def az_exists_batch(*args: Any, **kwargs: Any) -> Any: ...
async def az_list_batch(*args: Any, **kwargs: Any) -> Any: ...
async def az_head_batch(*args: Any, **kwargs: Any) -> Any: ...
async def az_is_dir(*args: Any, **kwargs: Any) -> Any: ...
async def az_is_dir_batch(*args: Any, **kwargs: Any) -> Any: ...
async def az_list_containers(*args: Any, **kwargs: Any) -> Any: ...
def az_presign(
    endpoint: str,
    container: str,
    blob_path: str,
    account_name: str,
    account_key: str | None = None,
    sas_token: str | None = None,
    method: str | None = None,
    expires: int | None = None,
) -> str: ...

# -- Artifactory --
async def art_get_batch(*args: Any, **kwargs: Any) -> Any: ...
async def art_put_batch(*args: Any, **kwargs: Any) -> Any: ...
async def art_copy_batch(*args: Any, **kwargs: Any) -> Any: ...
async def art_delete_batch(*args: Any, **kwargs: Any) -> Any: ...
async def art_exists_batch(*args: Any, **kwargs: Any) -> Any: ...
async def art_list_batch(*args: Any, **kwargs: Any) -> Any: ...
async def art_list_repos(*args: Any, **kwargs: Any) -> Any: ...
async def art_storage_info(*args: Any, **kwargs: Any) -> Any: ...

# -- HTTP --
async def http_get(*args: Any, **kwargs: Any) -> Any: ...
async def http_put(*args: Any, **kwargs: Any) -> Any: ...
async def http_post(*args: Any, **kwargs: Any) -> Any: ...
async def http_delete(*args: Any, **kwargs: Any) -> Any: ...
async def http_head(*args: Any, **kwargs: Any) -> Any: ...
async def http_patch(*args: Any, **kwargs: Any) -> Any: ...
async def http_options(*args: Any, **kwargs: Any) -> Any: ...
async def http_exists(*args: Any, **kwargs: Any) -> Any: ...
async def http_scrape_links(*args: Any, **kwargs: Any) -> Any: ...
async def http_request(*args: Any, **kwargs: Any) -> Any: ...

# -- Unified --
async def range_read(path: str, start: int, end: int, **kwargs: Any) -> bytes: ...

# -- SSH / SFTP --
async def ssh_read(*args: Any, **kwargs: Any) -> bytes: ...
async def ssh_read_range(*args: Any, **kwargs: Any) -> bytes: ...
async def ssh_write(*args: Any, **kwargs: Any) -> int: ...
async def ssh_exists(*args: Any, **kwargs: Any) -> bool: ...
async def ssh_stat(*args: Any, **kwargs: Any) -> Any: ...
async def ssh_lstat(*args: Any, **kwargs: Any) -> Any: ...
async def ssh_setstat(*args: Any, **kwargs: Any) -> None: ...
async def ssh_list(*args: Any, **kwargs: Any) -> Any: ...
async def ssh_mkdir(*args: Any, **kwargs: Any) -> None: ...
async def ssh_rmdir(*args: Any, **kwargs: Any) -> None: ...
async def ssh_unlink(*args: Any, **kwargs: Any) -> None: ...
async def ssh_rename(*args: Any, **kwargs: Any) -> None: ...
def ssh_resolve_config(
    host: str, config_paths: list[str]
) -> tuple[str | None, int | None, str | None, str | None]: ...
def ssh_disconnect_all() -> None: ...
