# Copyright (C) 2026 Axis Communications AB, Lund, Sweden
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable, Callable
from os import PathLike, stat_result
from pathlib import Path
from typing import Any, Self, TypeAlias

from anyio import AsyncFile
from anyio import Path as AioPath

class BackendOptions:
    headers: dict[str, str]
    query: dict[str, str]
    provider: dict[str, Any]

class AccessGrant:
    principal: str
    actions: frozenset[str]
    def __init__(self, principal: str, actions: frozenset[str]) -> None: ...

class AccessPolicy:
    owner: str | None
    group: str | None
    grants: tuple[AccessGrant, ...]
    provider: dict[str, Any]
    def __init__(
        self,
        *,
        owner: str | None = None,
        group: str | None = None,
        grants: tuple[AccessGrant, ...] = (),
        provider: dict[str, Any] = {},
    ) -> None: ...

class AccessPolicyPatch:
    owner: str | None
    group: str | None
    grants: tuple[AccessGrant, ...]
    provider: dict[str, Any]
    def __init__(
        self,
        *,
        owner: str | None = None,
        group: str | None = None,
        grants: tuple[AccessGrant, ...] = (),
        provider: dict[str, Any] = {},
    ) -> None: ...

PathPart: TypeAlias = str | Path | AioPath | PathLike[str] | PathLike[bytes] | AsAnyPurePath

PROTOCOL_MAP: dict[str, type[AsAnyPurePath]]

class AsAnyPurePath:
    def __new__(cls, arg: PathPart = ".", *args: PathPart, **kwargs: Any) -> Self: ...
    def __rtruediv__(self, other: str | PathLike[str]) -> Self: ...
    def __truediv__(self, other: str | PathLike[str]) -> Self: ...
    @property
    def anchor(self) -> str: ...
    def as_posix(self) -> str: ...
    def as_uri(self) -> str: ...
    @property
    def drive(self) -> str: ...
    def full_match(self, pattern: str, *, case_sensitive: bool | None = None) -> bool: ...
    def is_absolute(self) -> bool: ...
    def is_relative_to(self, other: str | PathLike[str]) -> bool: ...
    def joinpath(self, *args: str | PathLike[str]) -> Self: ...
    def match(self, pattern: str, *, case_sensitive: bool | None = None) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def parent(self) -> Self: ...
    @property
    def parents(self) -> tuple[Self, ...]: ...
    @property
    def parts(self) -> tuple[str, ...]: ...
    def relative_to(self, *other: str | PathLike[str], walk_up: bool = False) -> Self: ...
    @property
    def root(self) -> str: ...
    @property
    def stem(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def suffixes(self) -> list[str]: ...
    def with_name(self, name: str) -> Self: ...
    def with_parent(self, parent: str | PathLike[str] | Self) -> Self: ...
    def with_segments(self, *pathsegments: str | PathLike[str] | Self) -> Self: ...
    def with_stem(self, stem: str) -> Self: ...
    def with_suffix(self, suffix: str) -> Self: ...

class AsAnyPath(AsAnyPurePath):
    def __new__(cls, arg: PathPart = ".", *args: PathPart, **kwargs: Any) -> Self: ...
    def __bytes__(self) -> bytes: ...
    def __fspath__(self) -> str: ...
    def absolute(self) -> Self: ...
    def chmod(self, mode: int, *, follow_symlinks: bool = True) -> None: ...
    @classmethod
    def cwd(cls) -> Self: ...
    async def exists(self) -> bool: ...
    def expanduser(self) -> Self: ...
    async def get_access_policy(
        self, *, backend_options: BackendOptions | None = None
    ) -> AccessPolicy: ...
    async def glob(
        self, pattern: str, *, case_sensitive: bool | None = None
    ) -> AsyncIterator[Self]: ...
    def group(self) -> str: ...
    def hardlink_to(self, target: str | bytes | PathLike[str] | PathLike[bytes]) -> None: ...
    @classmethod
    def home(cls) -> Self: ...
    def is_block_device(self) -> bool: ...
    def is_char_device(self) -> bool: ...
    async def is_dir(self) -> bool: ...
    def is_fifo(self) -> bool: ...
    async def is_file(self) -> bool: ...
    def is_junction(self) -> bool: ...
    def is_mount(self) -> bool: ...
    def is_socket(self) -> bool: ...
    def is_symlink(self) -> bool: ...
    async def iterdir(self) -> AsyncIterator[Self]: ...
    def lchmod(self, mode: int) -> None: ...
    def lstat(self) -> stat_result: ...
    async def mkdir(
        self, mode: int = 0o777, parents: bool = False, exist_ok: bool = False
    ) -> None: ...
    async def copy(
        self,
        dst: PathPart,
        *,
        recursive: bool = False,
        remove_src: bool = False,
        force: bool = False,
        atomic: bool = False,
        chunk_size: int | None = None,
        destination_backend_options: BackendOptions | None = None,
        on_progress: Callable[[int, int, Self, Self], None | Awaitable[None]] | None = None,
        on_done: Callable[[Self, Self, int, bool, BaseException | None], None | Awaitable[None]]
        | None = None,
    ) -> Self: ...
    async def move(
        self,
        target: PathPart,
        *,
        force: bool = False,
        atomic: bool = False,
        chunk_size: int | None = None,
        destination_backend_options: BackendOptions | None = None,
    ) -> Self: ...
    def open(
        self,
        mode: str = "r",
        buffering: int = -1,
        encoding: str | None = None,
        errors: str | None = None,
        newline: str | None = None,
        *,
        backend_options: BackendOptions | None = None,
    ) -> AsyncFile[Any]: ...
    def owner(self) -> str: ...
    async def read_bytes(self) -> bytes: ...
    def iter_bytes(self, chunk_size: int | None = None) -> AsyncIterator[bytes]: ...
    async def read_text(
        self, encoding: str | None = None, errors: str | None = None, newline: str | None = None
    ) -> str: ...
    def readlink(self) -> Self: ...
    async def rename(
        self,
        target: PathPart,
        *,
        force: bool = False,
        atomic: bool = False,
        chunk_size: int | None = None,
        destination_backend_options: BackendOptions | None = None,
    ) -> Self: ...
    async def replace(
        self, target: PathPart, *, destination_backend_options: BackendOptions | None = None
    ) -> Self: ...
    def resolve(self, strict: bool = False) -> Self: ...
    async def rglob(
        self, pattern: str, *, case_sensitive: bool | None = None
    ) -> AsyncIterator[Self]: ...
    async def rmdir(self) -> None: ...
    def samefile(self, other_path: str | PathLike[str]) -> bool: ...
    async def stat(self, *, follow_symlinks: bool = True) -> stat_result: ...
    def symlink_to(
        self,
        target: str | bytes | PathLike[str] | PathLike[bytes] | Self,
        target_is_directory: bool = False,
    ) -> None: ...
    async def touch(self, mode: int = 0o666, exist_ok: bool = True) -> None: ...
    async def unlink(self, missing_ok: bool = False) -> None: ...
    async def update_access_policy(
        self,
        policy_patch: AccessPolicyPatch,
        *,
        backend_options: BackendOptions | None = None,
    ) -> None: ...
    async def walk(
        self,
        top_down: bool = True,
        on_error: Callable[[OSError], object] | None = None,
        follow_symlinks: bool = False,
    ) -> AsyncIterator[tuple[Self, list[str], list[str]]]: ...
    async def write_bytes(
        self, data: bytes, *, backend_options: BackendOptions | None = None
    ) -> int: ...
    async def write_text(
        self,
        data: str,
        encoding: str | None = None,
        errors: str | None = None,
        newline: str | None = None,
        *,
        backend_options: BackendOptions | None = None,
    ) -> int: ...
    async def checksums(self) -> dict[str, str]: ...

def register_protocol(protocol: str, path_class: type[AsAnyPurePath]) -> None: ...
def list_protocols() -> list[str]: ...
